-- CHẠY TRONG MYSQL WORKBENCH
-- Tạo cơ sở dữ liệu QLCHUNGCHI và các bảng trong đó

DROP DATABASE IF EXISTS QLCHUNGCHI;
CREATE DATABASE QLCHUNGCHI;
USE QLCHUNGCHI;

-- ===== Bảng không phụ thuộc =====
DROP TABLE IF EXISTS TAIKHOAN;
CREATE TABLE TAIKHOAN (
    MA_TK CHAR(10),
    TEN_DANGNHAP CHAR(25),
    MATKHAU CHAR(25),
    PRIMARY KEY (MA_TK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS PHONGTHI;
CREATE TABLE PHONGTHI (
    MA_PHONG CHAR(10),
    TEN_PHONG VARCHAR(50),
    SUCCHUA INT,
    DIADIEM VARCHAR(100),
    PRIMARY KEY (MA_PHONG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS DONVICHAMTHI;
CREATE TABLE DONVICHAMTHI (
    MA_DONVI CHAR(10),
    TEN_DONVI VARCHAR(50),
    PRIMARY KEY (MA_DONVI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== Bảng phụ thuộc TAIKHOAN =====
DROP TABLE IF EXISTS NHANVIEN;
CREATE TABLE NHANVIEN (
    MA_NV CHAR(10),
    HOTEN VARCHAR(50),
    NGAYSINH DATE,
    GIOITINH VARCHAR(3),
    SDT CHAR(10),
    EMAIL CHAR(50),
    DIACHI VARCHAR(100),
    LOAI_NV VARCHAR(25),
    TINHTRANG_COITHI VARCHAR(25),
    MA_TK CHAR(10),
    PRIMARY KEY (MA_NV),
    FOREIGN KEY (MA_TK) REFERENCES TAIKHOAN(MA_TK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS KHACHHANG;
CREATE TABLE KHACHHANG (
    MA_KH CHAR(10),
    TEN_KH VARCHAR(50),
    EMAIL CHAR(50),
    SDT CHAR(10),
    LOAI_KH VARCHAR(25),
    MA_TK CHAR(10),
    PRIMARY KEY (MA_KH),
    FOREIGN KEY (MA_TK) REFERENCES TAIKHOAN(MA_TK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== Bảng phụ thuộc PHONGTHI =====
DROP TABLE IF EXISTS LICHTHI;
CREATE TABLE LICHTHI (
    MA_LICHTHI CHAR(10),
    NGAYTHI DATE,
    GIOTHI TIME,
    LOAI_DANHGIA VARCHAR(10),
    SOLUONG_DANGKY INT,
    MA_PHONG CHAR(10),
    PRIMARY KEY (MA_LICHTHI),
    FOREIGN KEY (MA_PHONG) REFERENCES PHONGTHI(MA_PHONG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== Bảng phụ thuộc NHANVIEN, KHACHHANG, LICHTHI =====
DROP TABLE IF EXISTS PHIEUDANGKY;
CREATE TABLE PHIEUDANGKY (
    MA_PHIEUDANGKY CHAR(10),
    NGAYLAP DATE,
    TRANGTHAI_THANHTOAN VARCHAR(25),
    NV_LAP CHAR(10),
    MA_LICHTHI CHAR(10),
    MA_KH CHAR(10),
    PRIMARY KEY (MA_PHIEUDANGKY),
    FOREIGN KEY (NV_LAP) REFERENCES NHANVIEN(MA_NV),
    FOREIGN KEY (MA_KH) REFERENCES KHACHHANG(MA_KH),
    FOREIGN KEY (MA_LICHTHI) REFERENCES LICHTHI(MA_LICHTHI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== Bảng phụ thuộc NHANVIEN, KHACHHANG =====
DROP TABLE IF EXISTS PHIEUTHANHTOAN;
CREATE TABLE PHIEUTHANHTOAN (
    MA_PHIEUTHANHTOAN CHAR(10),
    NGAYLAP DATE,
    TRANGTHAI_THANHTOAN VARCHAR(25),
    TONGTIEN INT,
    NGAYTHANHTOAN DATE,
    GIAMGIA FLOAT,
    NV_LAP CHAR(10),
    MA_PHIEUDANGKY CHAR(10),
    MA_KH CHAR(10),
    PRIMARY KEY (MA_PHIEUTHANHTOAN),
    FOREIGN KEY (NV_LAP) REFERENCES NHANVIEN(MA_NV),
    FOREIGN KEY (MA_KH) REFERENCES KHACHHANG(MA_KH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== Bảng phụ thuộc NHANVIEN, KHACHHANG, PHIEUTHANHTOAN =====
DROP TABLE IF EXISTS HOADON;
CREATE TABLE HOADON (
    MA_HD CHAR(10),
    NGAYLAP DATE,
    TONGTIEN INT,
    PHUONGTHUC_THANHTOAN VARCHAR(25),
    NV_LAP CHAR(10),
    MA_PHIEUTHANHTOAN CHAR(10),
    MA_KH CHAR(10),
    PRIMARY KEY (MA_HD),
    FOREIGN KEY (NV_LAP) REFERENCES NHANVIEN(MA_NV),
    FOREIGN KEY (MA_PHIEUTHANHTOAN) REFERENCES PHIEUTHANHTOAN(MA_PHIEUTHANHTOAN),
    FOREIGN KEY (MA_KH) REFERENCES KHACHHANG(MA_KH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== Bảng phụ thuộc LICHTHI, NHANVIEN =====
DROP TABLE IF EXISTS PHANCONGCOITHI;
CREATE TABLE PHANCONGCOITHI (
    MA_LICHTHI CHAR(10),
    MA_NV CHAR(10),
    PRIMARY KEY (MA_LICHTHI, MA_NV),
    FOREIGN KEY (MA_LICHTHI) REFERENCES LICHTHI(MA_LICHTHI),
    FOREIGN KEY (MA_NV) REFERENCES NHANVIEN(MA_NV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== Bảng phụ thuộc PHIEUDANGKY, KHACHHANG =====
DROP TABLE IF EXISTS THISINH;
CREATE TABLE THISINH (
    MA_TS CHAR(10),
    HOTEN VARCHAR(50),
    NGAYSINH DATE,
    GIOITINH VARCHAR(3),
    EMAIL CHAR(50),
    SDT CHAR(10),
    CCCD CHAR(12),
    DIACHI VARCHAR(100),
    MA_KH CHAR(10),
    MA_PHIEUDANGKY CHAR(10),
    PRIMARY KEY (MA_TS),
    FOREIGN KEY (MA_KH) REFERENCES KHACHHANG(MA_KH),
    FOREIGN KEY (MA_PHIEUDANGKY) REFERENCES PHIEUDANGKY(MA_PHIEUDANGKY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== Bảng phụ thuộc THISINH, LICHTHI, NHANVIEN, PHIEUDANGKY =====
DROP TABLE IF EXISTS PHIEUDUTHI;
CREATE TABLE PHIEUDUTHI (
    MA_PHIEUDUTHI CHAR(10),
    LAN_GIAHAN INT,
    MA_PHIEUDANGKY CHAR(10),
    NV_LAP CHAR(10),
    MA_LICHTHI CHAR(10),
    MA_TS CHAR(10),
    PRIMARY KEY (MA_PHIEUDUTHI),
    FOREIGN KEY (MA_PHIEUDANGKY) REFERENCES PHIEUDANGKY(MA_PHIEUDANGKY),
    FOREIGN KEY (NV_LAP) REFERENCES NHANVIEN(MA_NV),
    FOREIGN KEY (MA_LICHTHI) REFERENCES LICHTHI(MA_LICHTHI),
    FOREIGN KEY (MA_TS) REFERENCES THISINH(MA_TS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== Bảng phụ thuộc PHIEUDUTHI, LICHTHI, DONVICHAMTHI =====
DROP TABLE IF EXISTS BAITHI;
CREATE TABLE BAITHI (
    MA_BAITHI CHAR(10),
    TEN_BAITHI VARCHAR(50),
    HINHTHUCTHI VARCHAR(25),
    THOIGIANTHI INT,
    MA_PHIEUDUTHI CHAR(10),
    MA_LICHTHI CHAR(10),
    DONVICHAM CHAR(10),
    PRIMARY KEY (MA_BAITHI),
    FOREIGN KEY (MA_PHIEUDUTHI) REFERENCES PHIEUDUTHI(MA_PHIEUDUTHI),
    FOREIGN KEY (MA_LICHTHI) REFERENCES LICHTHI(MA_LICHTHI),
    FOREIGN KEY (DONVICHAM) REFERENCES DONVICHAMTHI(MA_DONVI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== Bảng phụ thuộc PHIEUDUTHI, NHANVIEN, KHACHHANG =====
DROP TABLE IF EXISTS PHIEUGIAHAN;
CREATE TABLE PHIEUGIAHAN (
    MA_PHIEUGIAHAN CHAR(10),
    LYDO_GIAHAN VARCHAR(100),
    NGAYLAP DATE,
    TINHTRANG_THANHTOAN VARCHAR(25),
    PHIGIAHAN INT,
    NV_LAP CHAR(10),
    MA_PHIEUDUTHI CHAR(10),
    PRIMARY KEY (MA_PHIEUGIAHAN),
    FOREIGN KEY (NV_LAP) REFERENCES NHANVIEN(MA_NV),
    FOREIGN KEY (MA_PHIEUDUTHI) REFERENCES PHIEUDUTHI(MA_PHIEUDUTHI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== Bảng phụ thuộc PHIEUDANGKY, KHACHHANG, NHANVIEN =====
DROP TABLE IF EXISTS CHUNGCHI;
CREATE TABLE CHUNGCHI (
    MA_CHUNGCHI CHAR(10),
    TENCHUNGCHI VARCHAR(50),
    KETQUA VARCHAR(3),
    DIEMSO INT,
    NGAYCAP DATE,
    NGAYHETHAN DATE,
    TRANGTHAINHAN VARCHAR(10),
    NV_GHINHAN CHAR(10),
    MA_PHIEUDUTHI CHAR(10),
    MA_KH CHAR(10),
    PRIMARY KEY (MA_CHUNGCHI),
    FOREIGN KEY (NV_GHINHAN) REFERENCES NHANVIEN(MA_NV),
    FOREIGN KEY (MA_PHIEUDUTHI) REFERENCES PHIEUDANGKY(MA_PHIEUDANGKY),
    FOREIGN KEY (MA_KH) REFERENCES KHACHHANG(MA_KH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== Kiểm tra =====
SELECT * FROM KHACHHANG;
SELECT * FROM BAITHI;
