USE master
GO
IF DB_ID('QLIHETHONGTTTHICHUNGCHI') IS NOT NULL
	DROP DATABASE QLIHETHONGTTTHICHUNGCHI
GO

CREATE DATABASE QLIHETHONGTTTHICHUNGCHI
GO

USE QLIHETHONGTTTHICHUNGCHI
GO

--Tài khoản online của khách hàng
CREATE TABLE TAIKHOAN
(
    MA_TK CHAR(10),
	TEN_DANGNHAP CHAR(25),
    MATKHAU CHAR(25)
	
    CONSTRAINT PK_ACCOUNT
    PRIMARY KEY (MA_TK)
);

CREATE TABLE NHANVIEN
(
	MA_NV CHAR(10),
	HOTEN NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(3),
	SDT CHAR(10),
	EMAIL CHAR(50),
	DIACHI NVARCHAR(100),
	LOAI_NV NVARCHAR(25),
	TINHTRANG_COITHI NVARCHAR(25),
	MA_TK CHAR(10)
	
	CONSTRAINT PK_NHANVIEN
	PRIMARY KEY (MA_NV),

	CONSTRAINT FK_NHANVIEN_TAIKHOAN
	FOREIGN KEY(MA_TK)
	REFERENCES TAIKHOAN
)

CREATE TABLE KHACHHANG
(
	MA_KH CHAR(10),
	TEN_KH NVARCHAR(50),
	EMAIL CHAR(50),
	SDT CHAR(10),
	LOAI_KH NVARCHAR(25),
	MA_TK CHAR(10)

	CONSTRAINT PK_KHACHHANG
	PRIMARY KEY (MA_KH),

	CONSTRAINT FK_KHACHHANG_TAIKHOAN
	FOREIGN KEY(MA_TK)
	REFERENCES TAIKHOAN
)

CREATE TABLE HOADON
(
	MA_HD CHAR(10),
	NGAYLAP DATE,
	TONGTIEN INT,
	PHUONGTHUC_THANHTOAN NVARCHAR(25),
	NV_LAP CHAR(10),
	MA_PHIEUTHANHTOAN CHAR(10),
	MA_KH CHAR(10)

	CONSTRAINT PK_HOADON
	PRIMARY KEY (MA_HD),

	CONSTRAINT FK_HOADON_NHANVIEN
	FOREIGN KEY(NV_LAP)
	REFERENCES NHANVIEN,

	CONSTRAINT FK_HOADON_KHACHHANG
	FOREIGN KEY(MA_KH)
	REFERENCES KHACHHANG
)

CREATE TABLE PHIEUTHANHTOAN
(
	MA_PHIEUTHANHTOAN CHAR(10),
	NGAYLAP DATE,
	TRANGTHAI_THANHTOAN NVARCHAR(25),
	TONGTIEN INT,
	NGAYTHANHTOAN DATE,
	GIAMGIA FLOAT,
	NV_LAP CHAR(10),
	MA_PHIEUDANGKY CHAR(10),
	MA_KH CHAR(10)

	CONSTRAINT PK_PHIEUTHANHTOAN
	PRIMARY KEY (MA_PHIEUTHANHTOAN),

	CONSTRAINT FK_PHIEUTHANHTOAN_NHANVIEN
	FOREIGN KEY(NV_LAP)
	REFERENCES NHANVIEN,

	CONSTRAINT FK_PHIEUTHANHTOAN_KHACHHANG
	FOREIGN KEY(MA_KH)
	REFERENCES KHACHHANG
)

ALTER TABLE HOADON
ADD 
	CONSTRAINT FK_HOADON_PHIEUTHANHTOAN
	FOREIGN KEY(MA_PHIEUTHANHTOAN)
	REFERENCES PHIEUTHANHTOAN

CREATE TABLE PHIEUDANGKY
(
	MA_PHIEUDANGKY CHAR(10),
	NGAYLAP DATE,
	TRANGTHAI_THANHTOAN NVARCHAR(25),
	NV_LAP CHAR(10),
	MA_LICHTHI CHAR(10),
	MA_KH CHAR(10)

	CONSTRAINT PK_PHIEUDANGKY
	PRIMARY KEY (MA_PHIEUDANGKY),

	CONSTRAINT FK_PHIEUDANGKY_NHANVIEN
	FOREIGN KEY(NV_LAP)
	REFERENCES NHANVIEN,

	CONSTRAINT FK_PHIEUDANGKY_KHACHHANG
	FOREIGN KEY(MA_KH)
	REFERENCES KHACHHANG
)

ALTER TABLE PHIEUTHANHTOAN
ADD
	CONSTRAINT FK_PHIEUTHANHTOAN_PHIEUDANGKY
	FOREIGN KEY(MA_PHIEUDANGKY)
	REFERENCES PHIEUDANGKY

CREATE TABLE PHONGTHI
(
	MA_PHONG CHAR(10),
	TEN_PHONG NVARCHAR(50),
	SUCCHUA INT, 
	DIADIEM NVARCHAR(100)

	CONSTRAINT PK_PHONGTHI
	PRIMARY KEY (MA_PHONG)
)

CREATE TABLE LICHTHI
(
	MA_LICHTHI CHAR(10),
	NGAYTHI DATE,
	GIOTHI TIME,
	LOAI_DANHGIA NVARCHAR(10),
	SOLUONG_DANGKY INT,
	MA_PHONG CHAR(10)

	CONSTRAINT PK_LICHTHI
	PRIMARY KEY (MA_LICHTHI),

	CONSTRAINT FK_LICHTHI_PHONGTHI
	FOREIGN KEY(MA_PHONG)
	REFERENCES PHONGTHI
)

ALTER TABLE PHIEUDANGKY
ADD		
	CONSTRAINT FK_PHIEUDANGKY_LICHTHI
	FOREIGN KEY(MA_LICHTHI)
	REFERENCES LICHTHI

CREATE TABLE PHANCONGCOITHI
(
	MA_LICHTHI CHAR(10),
	MA_NV CHAR(10)

	CONSTRAINT PK_PHANCONGCOITHI
	PRIMARY KEY (MA_LICHTHI, MA_NV),

	CONSTRAINT FK_PHANCONGCOITHI_LICHTHI
	FOREIGN KEY(MA_LICHTHI)
	REFERENCES LICHTHI,

	CONSTRAINT FK_PHANCONGCOITHI_NHANVIEN
	FOREIGN KEY(MA_NV)
	REFERENCES NHANVIEN
)

CREATE TABLE DONVICHAMTHI
(
	MA_DONVI CHAR(10),
	TEN_DONVI NVARCHAR(50)

	CONSTRAINT PK_DONVICHAMTHI
	PRIMARY KEY (MA_DONVI)
)

CREATE TABLE THISINH
(
	MA_TS CHAR(10),
	HOTEN NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(3),
	EMAIL CHAR(50),
	SDT CHAR(10),
	CCCD CHAR(12),
	DIACHI NVARCHAR(100),
	MA_KH CHAR(10),
	MA_PHIEUDANGKY CHAR(10)

	CONSTRAINT PK_THISINH
	PRIMARY KEY (MA_TS),

	CONSTRAINT FK_THISINH_KHACHHANG
	FOREIGN KEY(MA_KH)
	REFERENCES KHACHHANG,

	CONSTRAINT FK_THISINH_PHIEUDANGKY
	FOREIGN KEY(MA_PHIEUDANGKY)
	REFERENCES PHIEUDANGKY
)

CREATE TABLE PHIEUDUTHI
(
	MA_PHIEUDUTHI CHAR(10),
	LAN_GIAHAN INT,
	MA_PHIEUDANGKY CHAR(10),
	NV_LAP CHAR(10),
	MA_LICHTHI CHAR(10),
	MA_TS CHAR(10)

	CONSTRAINT PK_PHIEUDUTHI
	PRIMARY KEY (MA_PHIEUDUTHI),

	CONSTRAINT FK_PHIEUDUTHI_NHANVIEN
	FOREIGN KEY(NV_LAP)
	REFERENCES NHANVIEN,

	CONSTRAINT FK_PHIEUDUTHI_LICHTHI
	FOREIGN KEY(MA_LICHTHI)
	REFERENCES LICHTHI,

	CONSTRAINT FK_PHIEUDUTHI_PHIEUDANGKY
	FOREIGN KEY(MA_PHIEUDANGKY)
	REFERENCES PHIEUDANGKY,

	CONSTRAINT FK_PHIEUDUTHI_THISINH
	FOREIGN KEY(MA_TS)
	REFERENCES THISINH
)

CREATE TABLE BAITHI
(
	MA_BAITHI CHAR(10),
	TEN_BAITHI NVARCHAR(50),
	HINHTHUCTHI NVARCHAR(25),
	THOIGIANTHI INT,
	MA_PHIEUDUTHI CHAR(10),
	MA_LICHTHI CHAR(10),
	DONVICHAM CHAR(10)

	CONSTRAINT PK_BAITHI
	PRIMARY KEY (MA_BAITHI),

	CONSTRAINT FK_BAITHI_DONVICHAMTHI
	FOREIGN KEY(DONVICHAM)
	REFERENCES DONVICHAMTHI,

	CONSTRAINT FK_BAITHI_LICHTHI
	FOREIGN KEY(MA_LICHTHI)
	REFERENCES LICHTHI,

	CONSTRAINT FK_BAITHI_PHIEUDUTHI
	FOREIGN KEY(MA_PHIEUDUTHI)
	REFERENCES PHIEUDUTHI
)

CREATE TABLE CHUNGCHI
(
	MA_CHUNGCHI CHAR(10),
	TENCHUNGCHI NVARCHAR(50),
	KETQUA NVARCHAR(3),
	DIEMSO INT,
	NGAYCAP DATE,
	NGAYHETHAN DATE,
	TRANGTHAINHAN NVARCHAR(10),
	NV_GHINHAN CHAR(10),
	MA_PHIEUDUTHI CHAR(10),
	MA_KH CHAR(10)

	CONSTRAINT PK_CHUNGCHI
	PRIMARY KEY (MA_CHUNGCHI),

	CONSTRAINT FK_CHUNGCHI_NHANVIEN
	FOREIGN KEY(NV_GHINHAN)
	REFERENCES NHANVIEN,

	CONSTRAINT FK_CHUNGCHI_PHIEUDUTHI
	FOREIGN KEY(MA_PHIEUDUTHI)
	REFERENCES PHIEUDANGKY,

	CONSTRAINT FK_CHUNGCHI_KHACHHANG
	FOREIGN KEY(MA_KH)
	REFERENCES KHACHHANG
)

CREATE TABLE PHIEUGIAHAN
(
	MA_PHIEUGIAHAN CHAR(10),
	LYDO_GIAHAN NVARCHAR(100),
	NGAYLAP DATE,
	TINHTRANG_THANHTOAN NVARCHAR(25),
	PHIGIAHAN INT,
	NV_LAP CHAR(10),
	MA_PHIEUDUTHI CHAR(10)

	CONSTRAINT PK_PHIEUGIAHAN
	PRIMARY KEY (MA_PHIEUGIAHAN),

	CONSTRAINT FK_PHIEUGIAHAN_NHANVIEN
	FOREIGN KEY(NV_LAP)
	REFERENCES NHANVIEN,

	CONSTRAINT FK_PHIEUGIAHAN_PHIEUDUTHI
	FOREIGN KEY(MA_PHIEUDUTHI)
	REFERENCES PHIEUDUTHI
)